<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:be.vlaanderen.bodemenondergrond.data.id.graph:codelijst-leesgroep">
  <xs:simpleType name="be.vlaanderen.bodemenondergrond.data.id.conceptscheme.leesgroep">
    <xs:restriction base="xs:string">
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/leesgroep/cmon" />
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/leesgroep/cte" />
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/leesgroep/dovpartners" />
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/leesgroep/thkpfas" />
    </xs:restriction>
  </xs:simpleType>
</xs:schema>
